### ISSUE TITLE
Implement an identity option for registering functions

### ISSUE THREAD

**Issue by to24toro** [Qiskit-Extensions/arraylias#15]
### What is the expected behavior?
When using a custom function, there are some cases where you simply want to return the input variable as it is. Currently, the implementation for such an identity function would look like this.

```
@alias.register_function(lib="array" path="some_function")
    def _(op):
        return op
```

To avoid the repetitive task of writing the identity function, we can introduce an "identity" option to the register_function (and possibly register_default, register_callback). This allow us to use the below simple registration.

```
@alias.register_function(lib="array" path="some_function", identity=True)
```

This modification will result in getting the identity option True without explicitly defining it.

**Comment by DanPuzzuoli** [comment]
Going to close this for now as we didn't end up implementing this.
